### ISSUE TITLE
Unresolved dependency on `@typescript-eslint/utils`

### ISSUE THREAD

**Issue by donalmurtagh** [vitest-dev/eslint-plugin-vitest#543]
I installed the latest version 1.1.4. When I run eslint with yarn v4.5.0, I get the following error

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@typescript-eslint/utils' imported from /Users/me/my-app/node_modules/@vitest/eslint-plugin/dist/index.mjs
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36)
```

I resolved this by adding the following to `devDependencies` in `package.json`

```
"@typescript-eslint/utils": "^8.7.0",
```

It looks like this is a recurrence of #477

**Comment by veritem** [comment]
`@typescript-eslint/utils` is set as a peer dependency; this might be an issue with yarn.

**Comment by bknoles** [comment]
I ran into this as well.

The compiled code imports from both `typescript` and `@typescript-eslint/utils` (see the screenshot), so I think both could reasonably be included as `devDependencies` within this package.

I imagine the intent is not to enforce a version constraint of something as commonly installed in parent applications such as TypeScript, so maybe non-optional `peerDependencies` would make sense instead of the currently configured [optional peer dependency](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/package.json#L80)?

Now that NPM automatically installs peer dependencies by default, I was running in circles trying to figure out why ESLint was yelling at me about `@typescript-eslint/utils` not being installed.

![image](https://github.com/user-attachments/assets/fc79fd41-e293-47ac-a477-b12794f57efb)

**Comment by bknoles** [comment]
Update: looks like `@typescript-eslint/utils` has `typescript` as a (non-optional) `peerDependency`, so the minimum change necessary would be making `@typescript-eslint/utils` either a non-optional `peerDependency` or bringing it into `devDependencies`.

**Comment by pixelastic** [comment]
Hello @veritem and sorry to revive a closed issue.

I'm having the same issue, trying to import `@vitest/eslint-plugin` but being yelled at because it can't find `@typescript-eslint/utils` or `typescript`. I've temporarily fixed it by adding those deps to my own project.

When you mention "it should be fixed on the latest version", do you mean `v1.1.7` (current) or the next version you'll release?

**Comment by veritem** [comment]
It's already been fixed. Typescript will remain an optional dependancy, but `@typescript-eslint/utils` will also be installed as a peer dependency.

**Comment by adamreisnz** [comment]
This is not fixed, it still errors with:

`Cannot find package '@typescript-eslint/utils' imported from /Users/Adam/Sites/arist/arist/node_modules/@vitest/eslint-plugin/dist/index.mjs`

Despite not usign TypeScript, we are forced to install `@typescript-eslint/utils` as a dependency, and if we do that, we are also forced to install `typescript` itself as dependency.

So there doesn't seem to be a way to use this package without Typescript.
